// @flow

// Generated by thrift2flow at Fri Jan 04 2019 15:13:53 GMT-0500 (EST)
// Source: /Users/chrisng/thrift2flow/test-output/e5c405bb-50fb-4978-a3f1-c334a90e7d5b/types.thrift

export type MyEnumXXX = "OK" | "ERROR";
export const MyEnumValueMap = {
  OK: 1,
  ERROR: 2
};
