// @flow

// Generated by thrift2flow at Fri Jan 04 2019 15:11:18 GMT-0500 (EST)
// Source: /Users/chrisng/thrift2flow/test-output/60f1adcb-f722-4137-8ad0-e21c4c18c2b5/types.thrift

export type MyEnumXXX = "OK" | "ERROR";
export const MyEnumValueMap = {
  OK: 1,
  ERROR: 2
};
