// @flow

// Generated by thrift2flow at Fri Jan 04 2019 15:10:13 GMT-0500 (EST)
// Source: /Users/chrisng/thrift2flow/test-output/c215e3a7-f7c2-4c69-8002-5b7c9dcd7152/shared.thrift

import * as other from "./other";

export type ThingStructXXX = {| thing: other.ThingXXX |};

export type OtherStructXXX = {| num: number |};

export type OtherStructTypedefXXX = number;
