// @flow

// Generated by thrift2flow at Fri Jan 04 2019 15:22:35 GMT-0500 (EST)
// Source: /Users/chrisng/thrift2flow/test-output/16f953d5-7d15-4452-b316-b60a17063351/types.thrift

export type OptionalsXXX = {| f_byte?: number |};
