// @flow

// Generated by thrift2flow at Fri Jan 04 2019 15:04:40 GMT-0500 (EST)
// Source: /Users/chrisng/thrift2flow/test-output/50b2a31c-a86b-45d3-8548-a764a1a47290/any.thrift

export type ThingXXX = number;
