// @flow

// Generated by thrift2flow at Fri Jan 04 2019 15:04:40 GMT-0500 (EST)
// Source: /Users/chrisng/thrift2flow/test-output/50b2a31c-a86b-45d3-8548-a764a1a47290/shared.thrift

import * as _any from "./any";

export type MyStructXXX = {|
  a: _any.ThingXXX,
  b: { [string]: _any.ThingXXX },
  c: { [_any.ThingXXX]: string }
|};

export type MyTypedefXXX = _any.ThingXXX;

export const MyConst: _any.ThingXXX = 10;

export const MySet: _any.ThingXXX[] = [0];

export type MyUnionXXX = {| a: _any.ThingXXX |} | {| b: number |};
